/* Generated by voltc 0.1.0 — do not edit */
/*
  target: esp8000
  pointer_width: 32  fpu: false  ram: 81920 B  f_cpu: 80000000
  static data (approx): 0 bytes
  functions:
    setup  stack≤0 B
    loop  stack≤0 B
    pinmode  stack≤2 B
  board: ESP8000 (ESP8266) (esp8000)
  mcu:   ESP8266EX
  led:   pin 2
  fqbn:  esp8266:esp8266:generic
  os:    macos
  port:  /dev/cu.BensBoseheadphones
  build: xtensa-lx106-elf-gcc -nostdlib -ffreestanding -mlongcalls -Os -DICACHE_FLASH -Wl,-e,main <file.c> -o firmware
  flash: esptool.py --chip esp8266 -p /dev/cu.BensBoseheadphones write_flash -fs 4MB 0x0 firmware.bin
  or:    arduino-cli compile -b esp8266:esp8266:generic && arduino-cli upload -b esp8266:esp8266:generic -p /dev/cu.BensBoseheadphones
*/
#include <stdint.h>
#include <stdbool.h>
#define VOLT_BOARD_ESP8000 1
#define VOLT_FQBN "esp8266:esp8266:generic"

#include <stdint.h>

static inline uint32_t volt_sat_addu32(uint32_t a, uint32_t b) {
    uint32_t s = a + b;
    return (s < a) ? UINT32_MAX : s;
}
static inline uint32_t volt_sat_subu32(uint32_t a, uint32_t b) {
    return (a < b) ? 0u : (a - b);
}
static inline uint32_t volt_sat_mulu32(uint32_t a, uint32_t b) {
    uint64_t p = (uint64_t)a * (uint64_t)b;
    return (p > UINT32_MAX) ? UINT32_MAX : (uint32_t)p;
}

typedef enum {
    PinMode_Input = 0,
    PinMode_Output = 1,
    PinMode_InputPullup = 2
} PinMode;

typedef enum {
    Level_Low = 0,
    Level_High = 1
} Level;

#define LED_BUILTIN ((uint8_t)2)
#define A0 ((uint8_t)17)

void setup(void);
void loop(void);
void pin_mode(uint8_t pin, uint8_t mode);
void digital_write(uint8_t pin, uint8_t level);
uint8_t digital_read(uint8_t pin);
uint16_t analog_read(uint8_t pin);
void pinmode(uint8_t p, uint8_t mode);
void delay_ms(uint32_t ms);
void delay_us(uint32_t us);

void setup(void) {
    pinmode(LED_BUILTIN, PinMode_Output);
}
void loop(void) {
    digital_write(LED_BUILTIN, Level_High);
    delay_ms(500);
    digital_write(LED_BUILTIN, Level_Low);
    delay_ms(500);
}
void pinmode(uint8_t p, uint8_t mode) {
    pin_mode(p, mode);
}
#if !defined(ARDUINO)
int main(void) {
    setup();
    for (;;) {
        loop();
    }
}
#endif

/* board runtime */
/* ESP8266 / ESP8285 GPIO. ESP8000, NodeMCU, and ESP-12x LED is GPIO2. */

#include <stdint.h>

#define GPIO_OUT (*(volatile uint32_t *)0x60000300u)
#define GPIO_OUT_W1TS (*(volatile uint32_t *)0x60000304u)
#define GPIO_OUT_W1TC (*(volatile uint32_t *)0x60000308u)
#define GPIO_ENABLE_W1TS (*(volatile uint32_t *)0x60000310u)
#define GPIO_ENABLE_W1TC (*(volatile uint32_t *)0x60000314u)
#define GPIO_IN (*(volatile uint32_t *)0x60000318u)

void delay_ms(uint32_t ms) {
    for (uint32_t i = 0; i < ms; i++) {
        for (volatile uint32_t n = 0; n < 8000; n++) {
        }
    }
}

void delay_us(uint32_t us) {
    for (uint32_t i = 0; i < us; i++) {
        for (volatile uint32_t n = 0; n < 8; n++) {
        }
    }
}

void pin_mode(uint8_t pin, uint8_t mode) {
    if (pin > 16) {
        return;
    }
    uint32_t mask = 1u << pin;
    if (mode == 1) {
        GPIO_ENABLE_W1TS = mask;
    } else {
        GPIO_ENABLE_W1TC = mask;
    }
}

void digital_write(uint8_t pin, uint8_t level) {
    if (pin > 16) {
        return;
    }
    uint32_t mask = 1u << pin;
    if (level) {
        GPIO_OUT_W1TS = mask;
    } else {
        GPIO_OUT_W1TC = mask;
    }
}

uint8_t digital_read(uint8_t pin) {
    if (pin > 16) {
        return 0;
    }
    return (GPIO_IN & (1u << pin)) ? 1 : 0;
}

uint16_t analog_read(uint8_t pin) {
    (void)pin;
    return 0;
}

