use crate::ast::*;
use crate::board;
use crate::report;
use crate::sema::{FuncDef, IntTy, Program, Ty};
use crate::span::Ident;
use crate::target::{IsrStyle, Target};

pub fn emit_c(program: &Program, target: &Target) -> String {
    let board = board::find_board(target.name);
    let mut out = String::new();
    out.push_str("/* Generated by voltc 0.1.0 — do not edit */\n");
    out.push_str("/*\n");
    out.push_str(&report::render(program, target));
    if let Some(b) = board {
        out.push_str(&board::flash_comment(b));
    }
    out.push_str("*/\n");
    for inc in target.includes {
        out.push_str(&format!("#include {inc}\n"));
    }
    for inc in &program.c_includes {
        if inc.angled {
            out.push_str(&format!("#include <{}>\n", inc.path));
        } else {
            out.push_str(&format!("#include \"{}\"\n", inc.path));
        }
    }
    for (k, v) in target.defines {
        out.push_str(&format!("#define {k} {v}\n"));
    }
    if let Some(b) = board {
        out.push_str(&board::board_defines(b));
    }
    out.push_str("\n#include <stdint.h>\n");
    out.push_str(SAT_HELPERS);
    out.push('\n');

    for name in &program.peripherals {
        out.push_str(&format!("typedef struct {{ char _; }} {name};\n"));
        out.push_str(&format!("static {name} {name};\n\n"));
    }

    for en in &program.enums {
        out.push_str("typedef enum {\n");
        for (i, (name, value)) in en.variants.iter().enumerate() {
            let comma = if i + 1 == en.variants.len() { "" } else { "," };
            out.push_str(&format!("    {}_{name} = {value}{comma}\n", en.name));
        }
        out.push_str(&format!("}} {};\n\n", en.name));
    }

    for st in &program.structs {
        out.push_str("typedef struct {\n");
        for (name, ty) in &st.fields {
            out.push_str(&format!("    {};\n", c_decl(ty, name)));
        }
        out.push_str(&format!("}} {};\n\n", st.name));
    }

    for (name, ty) in &program.aliases {
        out.push_str(&format!("typedef {} {name};\n", c_type(ty)));
    }
    if !program.aliases.is_empty() {
        out.push('\n');
    }

    for c in &program.consts {
        out.push_str(&format!(
            "#define {} (({}){})\n",
            c.name,
            c_type(&c.ty),
            c.value
        ));
    }
    if !program.consts.is_empty() {
        out.push('\n');
    }

    for r in &program.regs {
        out.push_str(&format!(
            "#define {} (*((volatile {} *)(0x{:X}u)))\n",
            r.name,
            c_type(&r.ty),
            r.address
        ));
        for b in &r.bits {
            let mask = if b.width >= 64 {
                u64::MAX
            } else {
                (1u64 << b.width) - 1
            };
            out.push_str(&format!(
                "#define {}_{}_SHIFT {}\n#define {}_{}_MASK 0x{:X}u\n",
                r.name, b.name, b.start, r.name, b.name, mask << b.start
            ));
        }
    }
    if !program.regs.is_empty() {
        out.push('\n');
    }

    for pin in &program.pins {
        out.push_str(&format!(
            "#define {}_REG {}\n#define {}_SHIFT {}\n#define {}_MASK 0x{:X}u\n",
            pin.name,
            pin.reg,
            pin.name,
            pin.start,
            pin.name,
            ((1u64 << pin.width) - 1) << pin.start
        ));
    }
    if !program.pins.is_empty() {
        out.push('\n');
    }

    for s in &program.statics {
        let storage = if s.is_extern { "extern " } else { "static " };
        let init = s
            .init
            .as_ref()
            .map(|e| format!(" = {}", emit_expr(e, program)))
            .unwrap_or_default();
        out.push_str(&format!("{}{}{};\n", storage, c_decl(&s.ty, &s.name), init));
    }
    if !program.statics.is_empty() {
        out.push('\n');
    }

    for f in &program.funcs {
        if f.is_async {
            out.push_str(&emit_async_types(f));
        }
        out.push_str(&emit_fn_prototype(f));
        out.push_str(";\n");
    }
    out.push('\n');

    for f in &program.funcs {
        if f.body.is_none() {
            continue;
        }
        if f.is_async {
            out.push_str(&emit_async_fn(f, program));
        } else {
            out.push_str(&emit_fn(f, program));
        }
        out.push('\n');
        if let Some(vector) = interrupt_vector(f) {
            out.push_str(&emit_isr_thunk(f, &vector, target));
        }
    }

    let has_main = program
        .funcs
        .iter()
        .any(|f| f.name == "main" && f.body.is_some());
    let has_setup = program
        .funcs
        .iter()
        .any(|f| f.name == "setup" && f.body.is_some());
    let has_loop = program
        .funcs
        .iter()
        .any(|f| f.name == "loop" && f.body.is_some());
    if !has_main && has_setup && has_loop {
        out.push_str("#if !defined(ARDUINO)\nint main(void) {\n    setup();\n    for (;;) {\n        loop();\n    }\n}\n#endif\n");
    }

    out.push_str("\n/* board runtime */\n");
    out.push_str(board::runtime_c(target.family));
    out.push('\n');

    out
}

const SAT_HELPERS: &str = r#"
static inline uint32_t volt_sat_addu32(uint32_t a, uint32_t b) {
    uint32_t s = a + b;
    return (s < a) ? UINT32_MAX : s;
}
static inline uint32_t volt_sat_subu32(uint32_t a, uint32_t b) {
    return (a < b) ? 0u : (a - b);
}
static inline uint32_t volt_sat_mulu32(uint32_t a, uint32_t b) {
    uint64_t p = (uint64_t)a * (uint64_t)b;
    return (p > UINT32_MAX) ? UINT32_MAX : (uint32_t)p;
}
"#;

fn interrupt_vector(f: &FuncDef) -> Option<String> {
    f.attrs.iter().find_map(|a| {
        if a.name.name == "interrupt" {
            a.value.clone()
        } else {
            None
        }
    })
}

fn emit_isr_thunk(f: &FuncDef, vector: &str, target: &Target) -> String {
    let name = &f.c_name;
    match target.isr_style {
        IsrStyle::Avr => format!("ISR({vector}_vect) {{ {name}(); }}\n\n"),
        IsrStyle::CortexM => format!("void {vector}_Handler(void) {{ {name}(); }}\n\n"),
        IsrStyle::None => format!(
            "/* interrupt {vector} — no ISR wiring on target `{}` */\n\n",
            target.name
        ),
    }
}

fn linkage(f: &FuncDef) -> &'static str {
    if f.is_internal {
        "static "
    } else {
        ""
    }
}

fn emit_fn_prototype(f: &FuncDef) -> String {
    if f.is_async {
        return format!(
            "{}bool {}_poll({}_Frame* self)",
            linkage(f),
            f.c_name,
            f.c_name
        );
    }
    let params = if f.params.is_empty() {
        "void".into()
    } else {
        f.params
            .iter()
            .map(|(n, ty)| c_decl(ty, n))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!(
        "{}{} {}({params})",
        linkage(f),
        c_type(&f.return_ty),
        f.c_name
    )
}

fn emit_fn(f: &FuncDef, program: &Program) -> String {
    let mut out = String::new();
    out.push_str(&emit_fn_prototype(f));
    out.push(' ');
    if let Some(body) = &f.body {
        out.push_str(&emit_block(body, program, 0));
    }
    out
}

fn emit_async_types(f: &FuncDef) -> String {
    format!("typedef struct {{ int _state; }} {}_Frame;\n", f.c_name)
}

fn emit_async_fn(f: &FuncDef, program: &Program) -> String {
    let Some(body) = &f.body else {
        return String::new();
    };
    let segs = split_async(body);
    let mut out = String::new();
    out.push_str(&format!(
        "void {}_init({}_Frame* self) {{ self->_state = 0; }}\n\n",
        f.c_name, f.c_name
    ));
    out.push_str(&emit_fn_prototype(f));
    out.push_str(" {\n    switch (self->_state) {\n");
    for (i, (stmts, await_expr)) in segs.iter().enumerate() {
        out.push_str(&format!("    case {i}: {{\n"));
        for stmt in stmts {
            out.push_str(&emit_stmt(stmt, program, 2));
        }
        if let Some(expr) = await_expr {
            out.push_str(&format!(
                "        (void)({});\n        self->_state = {};\n        return false;\n",
                emit_expr(expr, program),
                i + 1
            ));
        } else {
            out.push_str("        return true;\n");
        }
        out.push_str("    }\n");
    }
    out.push_str("    default: return true;\n    }\n}\n");
    out
}

fn split_async(block: &Block) -> Vec<(Vec<Stmt>, Option<Expr>)> {
    let mut segs = Vec::new();
    let mut cur = Vec::new();
    for stmt in &block.stmts {
        match stmt {
            Stmt::Await(expr, _) => {
                segs.push((std::mem::take(&mut cur), Some(expr.clone())));
            }
            other => cur.push(other.clone()),
        }
    }
    segs.push((cur, None));
    segs
}

fn emit_block(block: &Block, program: &Program, indent: usize) -> String {
    let mut out = String::from("{\n");
    for stmt in &block.stmts {
        out.push_str(&emit_stmt(stmt, program, indent + 1));
    }
    out.push_str(&pad(indent));
    out.push('}');
    out
}

fn emit_stmt(stmt: &Stmt, program: &Program, indent: usize) -> String {
    let p = pad(indent);
    match stmt {
        Stmt::Local(l) => {
            let init = l
                .init
                .as_ref()
                .map(|e| format!(" = {}", emit_expr(e, program)))
                .unwrap_or_default();
            let qual = if l.is_const { "const " } else { "" };
            format!(
                "{p}{}{}{};\n",
                qual,
                c_decl_from_ast(&l.ty, &l.name.name, program),
                init
            )
        }
        Stmt::Expr(e) => format!("{p}{};\n", emit_expr(e, program)),
        Stmt::Assign(a) => format!("{p}{};\n", emit_assign(a, program)),
        Stmt::If(i) => {
            let mut s = format!(
                "{p}if ({}) {}\n",
                emit_expr(&i.cond, program),
                emit_stmt_or_block(&i.then_branch, program, indent)
            );
            if let Some(e) = &i.else_branch {
                match e.as_ref() {
                    Stmt::If(_) => {
                        let inner = emit_stmt(e, program, indent);
                        s.push_str(&format!("{p}else {}", inner.trim_start()));
                    }
                    _ => {
                        s.push_str(&format!(
                            "{p}else {}\n",
                            emit_stmt_or_block(e, program, indent)
                        ));
                    }
                }
            }
            s
        }
        Stmt::While(w) => format!(
            "{p}while ({}) {}\n",
            emit_expr(&w.cond, program),
            emit_stmt_or_block(&w.body, program, indent)
        ),
        Stmt::For(f) => {
            let init = f
                .init
                .as_ref()
                .map(|s| strip_semi(&emit_stmt(s, program, 0)))
                .unwrap_or_default();
            let cond = f
                .cond
                .as_ref()
                .map(|e| emit_expr(e, program))
                .unwrap_or_default();
            let step = f
                .step
                .as_ref()
                .map(|e| emit_expr(e, program))
                .unwrap_or_default();
            format!(
                "{p}for ({init}; {cond}; {step}) {}\n",
                emit_stmt_or_block(&f.body, program, indent)
            )
        }
        Stmt::Loop(body) => format!("{p}for (;;) {}\n", emit_block(body, program, indent)),
        Stmt::Return(None, _) => format!("{p}return;\n"),
        Stmt::Return(Some(e), _) => format!("{p}return {};\n", emit_expr(e, program)),
        Stmt::Break(_) => format!("{p}break;\n"),
        Stmt::Continue(_) => format!("{p}continue;\n"),
        Stmt::Block(b) => format!("{p}{}\n", emit_block(b, program, indent)),
        Stmt::Match(m) => emit_match(m, program, indent),
        Stmt::When(w) => emit_when(w, program, indent),
        Stmt::Await(expr, _) => format!(
            "{p}/* await */ (void)({});\n",
            emit_expr(expr, program)
        ),
        Stmt::Asm(a) => emit_asm(a, program, indent),
    }
}

fn emit_assign(a: &AssignStmt, program: &Program) -> String {
    let rhs = emit_expr(&a.rhs, program);
    if let Some(rmw) = bitfield_rmw(&a.lhs, &rhs, &a.op, program) {
        return rmw;
    }
    if let ExprKind::Ident(id) = &a.lhs.kind {
        if let Some(pin) = program.pins.iter().find(|p| p.name == id.name) {
            return format!(
                "{0} = ({0} & ~(uint8_t){1}_MASK) | ((uint8_t)(({2}) << {1}_SHIFT))",
                pin.reg, pin.name, rhs
            );
        }
    }
    format!(
        "{} {} {}",
        emit_expr(&a.lhs, program),
        a.op.as_str(),
        rhs
    )
}

fn bitfield_rmw(lhs: &Expr, rhs: &str, op: &AssignOp, program: &Program) -> Option<String> {
    let ExprKind::Field(base, field) = &lhs.kind else {
        return None;
    };
    let ExprKind::Ident(reg_name) = &base.kind else {
        return None;
    };
    let reg = program.regs.iter().find(|r| r.name == reg_name.name)?;
    let bit = reg.bits.iter().find(|b| b.name == field.name)?;
    if !matches!(op, AssignOp::Eq) {
        return None;
    }
    let mask = if bit.width >= 64 {
        u64::MAX
    } else {
        ((1u64 << bit.width) - 1) << bit.start
    };
    Some(format!(
        "{0} = ({0} & ~(uint8_t)0x{mask:X}u) | ((uint8_t)((({rhs}) & {widthmask}) << {shift}))",
        reg.name,
        mask = mask,
        rhs = rhs,
        widthmask = (1u64 << bit.width) - 1,
        shift = bit.start
    ))
}

fn emit_match(m: &MatchStmt, program: &Program, indent: usize) -> String {
    let p = pad(indent);
    let scrut = emit_expr(&m.scrutinee, program);
    let mut out = String::new();
    for (i, arm) in m.arms.iter().enumerate() {
        let kw = if i == 0 { "if" } else { "else if" };
        match &arm.pattern {
            Pattern::Wildcard(_) => {
                out.push_str(&format!(
                    "{p}else {}\n",
                    emit_stmt_or_block(&arm.body, program, indent)
                ));
            }
            Pattern::Ident(id) => {
                out.push_str(&format!(
                    "{p}{kw} (({scrut}) == ({id})) {}\n",
                    emit_stmt_or_block(&arm.body, program, indent)
                ));
            }
            Pattern::Enum(en, var) => {
                out.push_str(&format!(
                    "{p}{kw} (({scrut}) == {}_{}) {}\n",
                    en.name,
                    var.name,
                    emit_stmt_or_block(&arm.body, program, indent)
                ));
            }
            Pattern::Int(lit, _) => {
                out.push_str(&format!(
                    "{p}{kw} (({scrut}) == {}) {}\n",
                    lit.raw,
                    emit_stmt_or_block(&arm.body, program, indent)
                ));
            }
        }
    }
    out
}

fn emit_when(w: &WhenStmt, program: &Program, indent: usize) -> String {
    let p = pad(indent);
    match w.taken {
        Some(true) => format!("{p}{}\n", emit_block(&w.then_branch, program, indent)),
        Some(false) => {
            if let Some(e) = &w.else_branch {
                format!("{p}{}\n", emit_block(e, program, indent))
            } else {
                format!("{p}/* when: false */\n")
            }
        }
        None => {
            let mut s = format!(
                "{p}if ({}) {}\n",
                emit_expr(&w.cond, program),
                emit_block(&w.then_branch, program, indent)
            );
            if let Some(e) = &w.else_branch {
                s.push_str(&format!("{p}else {}\n", emit_block(e, program, indent)));
            }
            s
        }
    }
}

fn emit_asm(a: &AsmStmt, program: &Program, indent: usize) -> String {
    let mut tpl = a.template.clone();
    for b in &a.binds {
        let needle = format!("{{{}}}", b.name.name);
        tpl = tpl.replace(&needle, &emit_expr(&b.value, program));
    }
    format!("{p}__asm__ volatile (\"{}\");\n", escape_str(&tpl), p = pad(indent))
}

fn emit_stmt_or_block(stmt: &Stmt, program: &Program, indent: usize) -> String {
    match stmt {
        Stmt::Block(b) => emit_block(b, program, indent),
        other => {
            let inner = emit_stmt(other, program, indent + 1);
            format!("{{\n{inner}{}}}", pad(indent))
        }
    }
}

fn emit_expr(expr: &Expr, program: &Program) -> String {
    match &expr.kind {
        ExprKind::Int(lit) => strip_bit_suffix(&lit.raw),
        ExprKind::Float(s) => s.clone(),
        ExprKind::Bool(true) => "true".into(),
        ExprKind::Bool(false) => "false".into(),
        ExprKind::Char(c) => format!("'{}'", escape_char(*c)),
        ExprKind::String(s) => format!("\"{}\"", escape_str(s)),
        ExprKind::Ident(id) => {
            if id.name == "target" {
                return "0".into();
            }
            if let Some(pin) = program.pins.iter().find(|p| p.name == id.name) {
                return format!(
                    "((({0}) >> {1}_SHIFT) & ((1u << {2}) - 1u))",
                    pin.reg, pin.name, pin.width
                );
            }
            id.name.clone()
        }
        ExprKind::Paren(inner) => format!("({})", emit_expr(inner, program)),
        ExprKind::Unary(op, inner) => match op {
            UnOp::PostInc => format!("{}++", emit_expr(inner, program)),
            UnOp::PostDec => format!("{}--", emit_expr(inner, program)),
            UnOp::PreInc => format!("++{}", emit_expr(inner, program)),
            UnOp::PreDec => format!("--{}", emit_expr(inner, program)),
            UnOp::AddrOf | UnOp::AddrOfMut => format!("&{}", emit_expr(inner, program)),
            other => format!("{}{}", other.as_str(), emit_expr(inner, program)),
        },
        ExprKind::Binary(op, lhs, rhs) => emit_binary(*op, lhs, rhs, program),
        ExprKind::Call(callee, args) => emit_call(expr, callee, args, program),
        ExprKind::Index(base, index) => {
            format!(
                "{}[{}]",
                emit_expr(base, program),
                emit_expr(index, program)
            )
        }
        ExprKind::Field(base, field) => emit_field(base, field, program),
        ExprKind::Cast(inner, ty) => {
            format!(
                "(({}) {})",
                c_type(&ast_ty_approx(ty, program)),
                emit_expr(inner, program)
            )
        }
        ExprKind::Await(inner) => emit_expr(inner, program),
    }
}

fn emit_binary(op: BinOp, lhs: &Expr, rhs: &Expr, program: &Program) -> String {
    let l = emit_expr(lhs, program);
    let r = emit_expr(rhs, program);
    match op {
        BinOp::WrapAdd => format!("((uint32_t)({l}) + (uint32_t)({r}))"),
        BinOp::WrapSub => format!("((uint32_t)({l}) - (uint32_t)({r}))"),
        BinOp::WrapMul => format!("((uint32_t)({l}) * (uint32_t)({r}))"),
        BinOp::SatAdd => format!("volt_sat_addu32((uint32_t)({l}), (uint32_t)({r}))"),
        BinOp::SatSub => format!("volt_sat_subu32((uint32_t)({l}), (uint32_t)({r}))"),
        BinOp::SatMul => format!("volt_sat_mulu32((uint32_t)({l}), (uint32_t)({r}))"),
        other => format!("({l} {} {r})", other.as_str()),
    }
}

fn emit_call(expr: &Expr, callee: &Expr, args: &[Expr], program: &Program) -> String {
    if let Some(rw) = program
        .call_rewrites
        .iter()
        .find(|r| r.span.start == expr.span.start && r.span.end == expr.span.end)
    {
        let mut cargs = Vec::new();
        if let ExprKind::Field(base, _) = &callee.kind {
            let recv = emit_expr(base, program);
            if rw.addr_of_recv {
                cargs.push(format!("&({recv})"));
            } else {
                cargs.push(recv);
            }
        }
        cargs.extend(args.iter().map(|a| emit_expr(a, program)));
        return format!("{}({})", rw.callee, cargs.join(", "));
    }
    let args = args
        .iter()
        .map(|a| emit_expr(a, program))
        .collect::<Vec<_>>()
        .join(", ");
    format!("{}({args})", emit_expr(callee, program))
}

fn emit_field(base: &Expr, field: &Ident, program: &Program) -> String {
    if let ExprKind::Ident(name) = &base.kind {
                if name.name == "target" {
            return match field.name.as_str() {
                "has_fpu" => if program.target_has_fpu {
                    "true"
                } else {
                    "false"
                }
                .to_string(),
                "pointer_width" => program.target_pointer_width.to_string(),
                "ram" => program.target_ram.to_string(),
                "f_cpu" => program.target_f_cpu.to_string(),
                _ => "0".into(),
            };
        }
        if program.enums.iter().any(|e| e.name == name.name) {
            return format!("{}_{}", name.name, field.name);
        }
        if let Some(reg) = program.regs.iter().find(|r| r.name == name.name) {
            if let Some(bit) = reg.bits.iter().find(|b| b.name == field.name) {
                let mask = if bit.width >= 64 {
                    u64::MAX
                } else {
                    (1u64 << bit.width) - 1
                };
                return format!("((({0} >> {1}) & 0x{mask:X}u))", name.name, bit.start);
            }
        }
    }
    let arrow = matches!(&base.kind, ExprKind::Unary(UnOp::Deref, _));
    let op = if arrow { "->" } else { "." };
    format!("{}{op}{}", emit_expr(base, program), field.name)
}

fn strip_bit_suffix(raw: &str) -> String {
    if let Some((num, _, _)) = split_raw_bit_suffix(raw) {
        num.to_string()
    } else {
        raw.to_string()
    }
}

fn split_raw_bit_suffix(raw: &str) -> Option<(&str, bool, u8)> {
    let bytes = raw.as_bytes();
    let mut i = bytes.len();
    while i > 0 && bytes[i - 1].is_ascii_digit() {
        i -= 1;
    }
    if i == 0 {
        return None;
    }
    let tag = bytes[i - 1] as char;
    if tag != 'u' && tag != 'i' {
        return None;
    }
    let num = &raw[..i - 1];
    let digits = &raw[i..];
    if num.is_empty() || digits.is_empty() {
        return None;
    }
    if !num.ends_with(|c: char| c.is_ascii_digit() || c == '_') {
        return None;
    }
    let width: u8 = digits.parse().ok()?;
    if !(1..=64).contains(&width) || matches!(width, 8 | 16 | 32 | 64) {
        return None;
    }
    Some((num, tag == 'i', width))
}

fn c_type(ty: &Ty) -> String {
    match ty {
        Ty::Void => "void".into(),
        Ty::Bool => "bool".into(),
        Ty::Int(i) => int_c(*i),
        Ty::Float(crate::sema::FloatTy::F32) => "float".into(),
        Ty::Float(crate::sema::FloatTy::F64) => "double".into(),
        Ty::Pointer(inner) | Ty::Ref { inner, .. } => format!("{}*", c_type(inner)),
        Ty::Array(inner, _) => c_type(inner),
        Ty::Struct(n) | Ty::Enum(n) | Ty::Peripheral(n) => n.clone(),
        Ty::Pin { .. } => "uint8_t".into(),
        Ty::IntLit => "int32_t".into(),
        Ty::FloatLit => "double".into(),
        Ty::Error => "void".into(),
    }
}

fn c_decl(ty: &Ty, name: &str) -> String {
    match ty {
        Ty::Array(inner, n) => format!("{} {name}[{n}]", c_type(inner)),
        Ty::Pointer(inner) | Ty::Ref { inner, .. } => match inner.as_ref() {
            Ty::Array(elem, n) => format!("{} (*{name})[{n}]", c_type(elem)),
            _ => format!("{} *{name}", c_type(inner)),
        },
        _ => format!("{} {name}", c_type(ty)),
    }
}

fn c_decl_from_ast(ty: &Type, name: &str, program: &Program) -> String {
    c_decl(&ast_ty_approx(ty, program), name)
}

fn ast_ty_approx(ty: &Type, program: &Program) -> Ty {
    match &ty.kind {
        TypeKind::Void | TypeKind::SelfTy => Ty::Void,
        TypeKind::Primitive(p) => match p {
            PrimitiveTy::Bool => Ty::Bool,
            PrimitiveTy::F32 => Ty::Float(crate::sema::FloatTy::F32),
            PrimitiveTy::F64 => Ty::Float(crate::sema::FloatTy::F64),
            other => Ty::Int(IntTy::from_prim(*other).unwrap()),
        },
        TypeKind::Bits { signed, width } => Ty::Int(IntTy::Bits {
            signed: *signed,
            width: *width,
        }),
        TypeKind::Named(n) => {
            if let Some((_, ty)) = program.aliases.iter().find(|(a, _)| a == &n.name) {
                return ty.clone();
            }
            Ty::Struct(n.name.clone())
        }
        TypeKind::Pointer(inner) => Ty::Pointer(Box::new(ast_ty_approx(inner, program))),
        TypeKind::Ref { inner, mutable } => Ty::Ref {
            mutable: *mutable,
            inner: Box::new(ast_ty_approx(inner, program)),
        },
        TypeKind::Array(inner, len) => {
            let n = match &len.kind {
                ExprKind::Int(lit) => lit.value as u64,
                _ => 0,
            };
            Ty::Array(Box::new(ast_ty_approx(inner, program)), n)
        }
    }
}

fn int_c(i: IntTy) -> String {
    match i {
        IntTy::Int => "int".into(),
        IntTy::I8 => "int8_t".into(),
        IntTy::I16 => "int16_t".into(),
        IntTy::I32 => "int32_t".into(),
        IntTy::I64 => "int64_t".into(),
        IntTy::Isize => "intptr_t".into(),
        IntTy::U8 => "uint8_t".into(),
        IntTy::U16 => "uint16_t".into(),
        IntTy::U32 => "uint32_t".into(),
        IntTy::U64 => "uint64_t".into(),
        IntTy::Usize => "uintptr_t".into(),
        IntTy::Bits { signed, width } => {
            let store = if width <= 8 {
                8
            } else if width <= 16 {
                16
            } else if width <= 32 {
                32
            } else {
                64
            };
            if signed {
                format!("int{store}_t")
            } else {
                format!("uint{store}_t")
            }
        }
    }
}

fn pad(n: usize) -> String {
    "    ".repeat(n)
}

fn strip_semi(s: &str) -> String {
    s.trim().trim_end_matches(';').trim().to_string()
}

fn escape_char(c: char) -> String {
    match c {
        '\n' => "\\n".into(),
        '\r' => "\\r".into(),
        '\t' => "\\t".into(),
        '\\' => "\\\\".into(),
        '\'' => "\\'".into(),
        '\0' => "\\0".into(),
        other => other.to_string(),
    }
}

fn escape_str(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '\n' => "\\n".into(),
            '\r' => "\\r".into(),
            '\t' => "\\t".into(),
            '\\' => "\\\\".into(),
            '"' => "\\\"".into(),
            other => other.to_string(),
        })
        .collect()
}
