use crate::ast::*;
use crate::sema::{FuncDef, IntTy, Program, Ty};
use crate::target::{IsrStyle, Target};

pub fn emit_c(program: &Program, target: &Target) -> String {
    let mut out = String::new();
    out.push_str("/* Generated by voltc 0.1.0 — do not edit */\n");
    for inc in target.includes {
        out.push_str(&format!("#include {inc}\n"));
    }
    for inc in &program.c_includes {
        if inc.angled {
            out.push_str(&format!("#include <{}>\n", inc.path));
        } else {
            out.push_str(&format!("#include \"{}\"\n", inc.path));
        }
    }
    for (k, v) in target.defines {
        out.push_str(&format!("#define {k} {v}\n"));
    }
    out.push('\n');

    for en in &program.enums {
        out.push_str("typedef enum {\n");
        for (i, (name, value)) in en.variants.iter().enumerate() {
            let comma = if i + 1 == en.variants.len() { "" } else { "," };
            out.push_str(&format!("    {}_{name} = {value}{comma}\n", en.name));
        }
        out.push_str(&format!("}} {};\n\n", en.name));
    }

    for st in &program.structs {
        out.push_str("typedef struct {\n");
        for (name, ty) in &st.fields {
            out.push_str(&format!("    {};\n", c_decl(ty, name)));
        }
        out.push_str(&format!("}} {};\n\n", st.name));
    }

    for c in &program.consts {
        out.push_str(&format!(
            "#define {} (({}){})\n",
            c.name,
            c_type(&c.ty),
            c.value
        ));
    }
    if !program.consts.is_empty() {
        out.push('\n');
    }

    for r in &program.regs {
        out.push_str(&format!(
            "#define {} (*((volatile {} *)(0x{:X}u)))\n",
            r.name,
            c_type(&r.ty),
            r.address
        ));
    }
    if !program.regs.is_empty() {
        out.push('\n');
    }

    for s in &program.statics {
        let storage = if s.is_extern { "extern " } else { "static " };
        let init = s
            .init
            .as_ref()
            .map(|e| format!(" = {}", emit_expr(e, program)))
            .unwrap_or_default();
        out.push_str(&format!("{}{}{};\n", storage, c_decl(&s.ty, &s.name), init));
    }
    if !program.statics.is_empty() {
        out.push('\n');
    }

    for f in &program.funcs {
        out.push_str(&emit_fn_prototype(f));
        out.push_str(";\n");
    }
    out.push('\n');

    for f in &program.funcs {
        if f.body.is_none() {
            continue;
        }
        out.push_str(&emit_fn(f, program));
        out.push('\n');
        if let Some(vector) = interrupt_vector(f) {
            out.push_str(&emit_isr_thunk(f, &vector, target));
        }
    }

    let has_main = program
        .funcs
        .iter()
        .any(|f| f.name == "main" && f.body.is_some());
    let has_setup = program
        .funcs
        .iter()
        .any(|f| f.name == "setup" && f.body.is_some());
    let has_loop = program
        .funcs
        .iter()
        .any(|f| f.name == "loop" && f.body.is_some());
    if !has_main && has_setup && has_loop {
        out.push_str("int main(void) {\n    setup();\n    for (;;) {\n        loop();\n    }\n}\n");
    }

    out
}

fn interrupt_vector(f: &FuncDef) -> Option<String> {
    f.attrs.iter().find_map(|a| {
        if a.name.name == "interrupt" {
            a.value.clone()
        } else {
            None
        }
    })
}

fn emit_isr_thunk(f: &FuncDef, vector: &str, target: &Target) -> String {
    match target.isr_style {
        IsrStyle::Avr => format!("ISR({vector}_vect) {{ {}(); }}\n\n", f.name),
        IsrStyle::CortexM => format!("void {vector}_Handler(void) {{ {}(); }}\n\n", f.name),
        IsrStyle::None => format!(
            "/* interrupt {vector} — no ISR wiring on target `{}` */\n\n",
            target.name
        ),
    }
}

fn emit_fn_prototype(f: &FuncDef) -> String {
    let params = if f.params.is_empty() {
        "void".into()
    } else {
        f.params
            .iter()
            .map(|(n, ty)| c_decl(ty, n))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("{} {}({params})", c_type(&f.return_ty), f.name)
}

fn emit_fn(f: &FuncDef, program: &Program) -> String {
    let mut out = String::new();
    out.push_str(&emit_fn_prototype(f));
    out.push(' ');
    if let Some(body) = &f.body {
        out.push_str(&emit_block(body, program, 0));
    }
    out
}

fn emit_block(block: &Block, program: &Program, indent: usize) -> String {
    let mut out = String::from("{\n");
    for stmt in &block.stmts {
        out.push_str(&emit_stmt(stmt, program, indent + 1));
    }
    out.push_str(&pad(indent));
    out.push('}');
    out
}

fn emit_stmt(stmt: &Stmt, program: &Program, indent: usize) -> String {
    let p = pad(indent);
    match stmt {
        Stmt::Local(l) => {
            let init = l
                .init
                .as_ref()
                .map(|e| format!(" = {}", emit_expr(e, program)))
                .unwrap_or_default();
            let qual = if l.is_const { "const " } else { "" };
            format!(
                "{p}{}{}{};\n",
                qual,
                c_decl_from_ast(&l.ty, &l.name.name, program),
                init
            )
        }
        Stmt::Expr(e) => format!("{p}{};\n", emit_expr(e, program)),
        Stmt::Assign(a) => format!(
            "{p}{} {} {};\n",
            emit_expr(&a.lhs, program),
            a.op.as_str(),
            emit_expr(&a.rhs, program)
        ),
        Stmt::If(i) => {
            let mut s = format!(
                "{p}if ({}) {}\n",
                emit_expr(&i.cond, program),
                emit_stmt_or_block(&i.then_branch, program, indent)
            );
            if let Some(e) = &i.else_branch {
                match e.as_ref() {
                    Stmt::If(_) => {
                        let inner = emit_stmt(e, program, indent);
                        s.push_str(&format!("{p}else {}", inner.trim_start()));
                    }
                    _ => {
                        s.push_str(&format!(
                            "{p}else {}\n",
                            emit_stmt_or_block(e, program, indent)
                        ));
                    }
                }
            }
            s
        }
        Stmt::While(w) => format!(
            "{p}while ({}) {}\n",
            emit_expr(&w.cond, program),
            emit_stmt_or_block(&w.body, program, indent)
        ),
        Stmt::For(f) => {
            let init = f
                .init
                .as_ref()
                .map(|s| strip_semi(&emit_stmt(s, program, 0)))
                .unwrap_or_default();
            let cond = f
                .cond
                .as_ref()
                .map(|e| emit_expr(e, program))
                .unwrap_or_default();
            let step = f
                .step
                .as_ref()
                .map(|e| emit_expr(e, program))
                .unwrap_or_default();
            format!(
                "{p}for ({init}; {cond}; {step}) {}\n",
                emit_stmt_or_block(&f.body, program, indent)
            )
        }
        Stmt::Loop(body) => format!("{p}for (;;) {}\n", emit_block(body, program, indent)),
        Stmt::Return(None, _) => format!("{p}return;\n"),
        Stmt::Return(Some(e), _) => format!("{p}return {};\n", emit_expr(e, program)),
        Stmt::Break(_) => format!("{p}break;\n"),
        Stmt::Continue(_) => format!("{p}continue;\n"),
        Stmt::Block(b) => format!("{p}{}\n", emit_block(b, program, indent)),
    }
}

fn emit_stmt_or_block(stmt: &Stmt, program: &Program, indent: usize) -> String {
    match stmt {
        Stmt::Block(b) => emit_block(b, program, indent),
        other => {
            let inner = emit_stmt(other, program, indent + 1);
            format!("{{\n{inner}{}}}", pad(indent))
        }
    }
}

fn emit_expr(expr: &Expr, program: &Program) -> String {
    match &expr.kind {
        ExprKind::Int(lit) => lit.raw.clone(),
        ExprKind::Float(s) => s.clone(),
        ExprKind::Bool(true) => "true".into(),
        ExprKind::Bool(false) => "false".into(),
        ExprKind::Char(c) => format!("'{}'", escape_char(*c)),
        ExprKind::String(s) => format!("\"{}\"", escape_str(s)),
        ExprKind::Ident(id) => id.name.clone(),
        ExprKind::Paren(inner) => format!("({})", emit_expr(inner, program)),
        ExprKind::Unary(op, inner) => match op {
            UnOp::PostInc => format!("{}++", emit_expr(inner, program)),
            UnOp::PostDec => format!("{}--", emit_expr(inner, program)),
            UnOp::PreInc => format!("++{}", emit_expr(inner, program)),
            UnOp::PreDec => format!("--{}", emit_expr(inner, program)),
            other => format!("{}{}", other.as_str(), emit_expr(inner, program)),
        },
        ExprKind::Binary(op, lhs, rhs) => format!(
            "({} {} {})",
            emit_expr(lhs, program),
            op.as_str(),
            emit_expr(rhs, program)
        ),
        ExprKind::Call(callee, args) => {
            let args = args
                .iter()
                .map(|a| emit_expr(a, program))
                .collect::<Vec<_>>()
                .join(", ");
            format!("{}({args})", emit_expr(callee, program))
        }
        ExprKind::Index(base, index) => {
            format!(
                "{}[{}]",
                emit_expr(base, program),
                emit_expr(index, program)
            )
        }
        ExprKind::Field(base, field) => {
            if let ExprKind::Ident(name) = &base.kind {
                if program.enums.iter().any(|e| e.name == name.name) {
                    return format!("{}_{}", name.name, field.name);
                }
            }
            let arrow =
                matches!(&base.kind, ExprKind::Unary(UnOp::Deref, _)) || field_from_pointer(base);
            let op = if arrow { "->" } else { "." };
            // If the user wrote `p.field` and p is a pointer, C needs `->`.
            // We don't have types on the AST here; emit `.` and also support `->`
            // from the source. Pointer+dot is rewritten in emit if the callee
            // used Arrow which both parse to Field.
            format!("{}{op}{}", emit_expr(base, program), field.name)
        }
        ExprKind::Cast(inner, ty) => {
            format!("(({}) {})", c_type_from_ast(ty), emit_expr(inner, program))
        }
    }
}

fn field_from_pointer(_base: &Expr) -> bool {
    false
}

fn c_type(ty: &Ty) -> String {
    match ty {
        Ty::Void => "void".into(),
        Ty::Bool => "bool".into(),
        Ty::Int(i) => int_c(*i).into(),
        Ty::Float(crate::sema::FloatTy::F32) => "float".into(),
        Ty::Float(crate::sema::FloatTy::F64) => "double".into(),
        Ty::Pointer(inner) => format!("{}*", c_type(inner)),
        Ty::Array(inner, _) => c_type(inner),
        Ty::Struct(n) | Ty::Enum(n) => n.clone(),
        Ty::IntLit => "int32_t".into(),
        Ty::FloatLit => "double".into(),
        Ty::Error => "void".into(),
    }
}

fn c_decl(ty: &Ty, name: &str) -> String {
    match ty {
        Ty::Array(inner, n) => format!("{} {name}[{n}]", c_type(inner)),
        Ty::Pointer(inner) => match inner.as_ref() {
            Ty::Array(elem, n) => format!("{} (*{name})[{n}]", c_type(elem)),
            _ => format!("{} *{name}", c_type(inner)),
        },
        _ => format!("{} {name}", c_type(ty)),
    }
}

fn c_decl_from_ast(ty: &Type, name: &str, _program: &Program) -> String {
    c_decl(&ast_ty_approx(ty), name)
}

fn c_type_from_ast(ty: &Type) -> String {
    c_type(&ast_ty_approx(ty))
}

fn ast_ty_approx(ty: &Type) -> Ty {
    match &ty.kind {
        TypeKind::Void => Ty::Void,
        TypeKind::Primitive(p) => match p {
            PrimitiveTy::Bool => Ty::Bool,
            PrimitiveTy::F32 => Ty::Float(crate::sema::FloatTy::F32),
            PrimitiveTy::F64 => Ty::Float(crate::sema::FloatTy::F64),
            other => Ty::Int(IntTy::from_prim(*other).unwrap()),
        },
        TypeKind::Named(n) => Ty::Struct(n.name.clone()),
        TypeKind::Pointer(inner) => Ty::Pointer(Box::new(ast_ty_approx(inner))),
        TypeKind::Array(inner, len) => {
            let n = match &len.kind {
                ExprKind::Int(lit) => lit.value as u64,
                _ => 0,
            };
            Ty::Array(Box::new(ast_ty_approx(inner)), n)
        }
    }
}

fn int_c(i: IntTy) -> &'static str {
    match i {
        IntTy::Int => "int",
        IntTy::I8 => "int8_t",
        IntTy::I16 => "int16_t",
        IntTy::I32 => "int32_t",
        IntTy::I64 => "int64_t",
        IntTy::Isize => "intptr_t",
        IntTy::U8 => "uint8_t",
        IntTy::U16 => "uint16_t",
        IntTy::U32 => "uint32_t",
        IntTy::U64 => "uint64_t",
        IntTy::Usize => "uintptr_t",
    }
}

fn pad(n: usize) -> String {
    "    ".repeat(n)
}

fn strip_semi(s: &str) -> String {
    s.trim().trim_end_matches(';').trim().to_string()
}

fn escape_char(c: char) -> String {
    match c {
        '\n' => "\\n".into(),
        '\r' => "\\r".into(),
        '\t' => "\\t".into(),
        '\\' => "\\\\".into(),
        '\'' => "\\'".into(),
        '\0' => "\\0".into(),
        other => other.to_string(),
    }
}

fn escape_str(s: &str) -> String {
    s.chars()
        .map(|c| match c {
            '\n' => "\\n".into(),
            '\r' => "\\r".into(),
            '\t' => "\\t".into(),
            '\\' => "\\\\".into(),
            '"' => "\\\"".into(),
            other => other.to_string(),
        })
        .collect()
}
